// Package openvpn provisions per-session client certificates against an
// easy-rsa PKI created at install time, and talks to a running openvpn
// server's management socket to pull live per-client telemetry and to force
// a session closed.
//
// OpenVPN is the secondary tunnel backend here (WireGuard is faster and is
// the recommended default): it exists for clients stuck behind
// firewalls/DPI that only let TLS-looking traffic on port 443 through,
// where OPENVPN_TCP is what actually gets a tunnel up at all.
package openvpn

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sync"
	"syscall"
)

var ErrPKINotInitialized = errors.New("openvpn: easy-rsa PKI not initialized (run scripts/30-openvpn-setup.sh first)")

// validName restricts certificate common names to a very small alphabet.
// Session IDs are generated by this same server (see httpapi/ids.go), but
// we still refuse to interpolate anything unexpected into a shell-exec'd
// argument list as defense in depth.
var validName = regexp.MustCompile(`^[A-Za-z0-9_-]{1,64}$`)

type PKI struct {
	dir string // EasyRSADir

	// mu serializes every easy-rsa invocation that mutates the PKI.
	//
	// easy-rsa is a shell wrapper around `openssl ca`, which keeps its
	// state in two shared files: pki/index.txt (the certificate database)
	// and pki/serial (the next serial number). Neither is written under a
	// lock, so concurrent issuance corrupts them. Measured here by issuing
	// 8 certificates in parallel against one PKI: two certificates came out
	// carrying the SAME serial, and only 7 of the 8 were recorded in
	// index.txt at all.
	//
	// Both outcomes break revocation, which is how a disconnect actually
	// ends an OpenVPN session:
	//   - a duplicate serial means revoking one session's certificate also
	//     revokes an unrelated user's, since the CRL lists serials;
	//   - a certificate missing from index.txt can never be revoked at all,
	//     because `easyrsa revoke` looks it up there — a credential that
	//     stays valid until the CA expires.
	//
	// Two users pressing connect at the same moment is ordinary traffic,
	// not an edge case, so this is serialized rather than hoped about.
	mu sync.Mutex
}

func NewPKI(easyRSADir string) *PKI {
	return &PKI{dir: easyRSADir}
}

// withPKILock serializes PKI mutations within this process (mu) and against
// any other process touching the same directory (an flock on the PKI dir).
//
// The in-process mutex alone is not enough: scripts/test-peer.sh and a
// manual `easyrsa` run by an operator use the same files, and the file lock
// is what keeps those from interleaving with a live /connect. A missing or
// unopenable lock file is not fatal — the mutex still holds — because
// refusing to connect would be a worse failure than the race it guards.
func (p *PKI) withPKILock(fn func() error) error {
	p.mu.Lock()
	defer p.mu.Unlock()

	lockPath := filepath.Join(p.dir, "pki", ".mobilvpn-ca.lock")
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return fn()
	}
	defer f.Close()
	if err := syscall.Flock(int(f.Fd()), syscall.LOCK_EX); err != nil {
		return fn()
	}
	defer func() { _ = syscall.Flock(int(f.Fd()), syscall.LOCK_UN) }()
	return fn()
}

func (p *PKI) easyrsaBin() string {
	return filepath.Join(p.dir, "easyrsa")
}

// Ready reports whether install-time PKI bootstrap has happened.
func (p *PKI) Ready() bool {
	_, err := os.Stat(filepath.Join(p.dir, "pki", "ca.crt"))
	return err == nil
}

type ClientCredential struct {
	CertPEM string
	KeyPEM  string
	CAPEM   string
	TAKey   string // tls-crypt static key shared by all clients of this server
}

// IssueClient generates a fresh, uniquely-named client certificate. name
// must already be a validated session ID; callers never pass raw user
// input here.
func (p *PKI) IssueClient(name string) (*ClientCredential, error) {
	if !validName.MatchString(name) {
		return nil, fmt.Errorf("openvpn: invalid certificate common name %q", name)
	}
	if !p.Ready() {
		return nil, ErrPKINotInitialized
	}

	if err := p.withPKILock(func() error {
		cmd := exec.Command(p.easyrsaBin(), "build-client-full", name, "nopass")
		cmd.Dir = p.dir
		cmd.Env = append(os.Environ(), "EASYRSA_BATCH=1")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("openvpn: easyrsa build-client-full failed: %w (%s)", err, truncate(out, 400))
		}
		return nil
	}); err != nil {
		return nil, err
	}

	cert, err := os.ReadFile(filepath.Join(p.dir, "pki", "issued", name+".crt"))
	if err != nil {
		return nil, fmt.Errorf("openvpn: reading issued cert: %w", err)
	}
	key, err := os.ReadFile(filepath.Join(p.dir, "pki", "private", name+".key"))
	if err != nil {
		return nil, fmt.Errorf("openvpn: reading issued key: %w", err)
	}
	ca, err := os.ReadFile(filepath.Join(p.dir, "pki", "ca.crt"))
	if err != nil {
		return nil, fmt.Errorf("openvpn: reading ca.crt: %w", err)
	}
	ta, err := os.ReadFile(filepath.Join(p.dir, "ta.key"))
	if err != nil {
		return nil, fmt.Errorf("openvpn: reading ta.key: %w", err)
	}

	return &ClientCredential{
		CertPEM: string(cert),
		KeyPEM:  string(key),
		CAPEM:   string(ca),
		TAKey:   string(ta),
	}, nil
}

// RevokeClient revokes a previously issued certificate and regenerates the
// CRL so the revocation takes effect on the *next* TLS handshake attempt.
// It does not drop an already-established session — pair this with
// Manager.KillSession to close the live tunnel immediately too.
func (p *PKI) RevokeClient(name string) error {
	if !validName.MatchString(name) {
		return fmt.Errorf("openvpn: invalid certificate common name %q", name)
	}
	cmd := exec.Command(p.easyrsaBin(), "revoke", name)
	cmd.Dir = p.dir
	cmd.Env = append(os.Environ(), "EASYRSA_BATCH=1")

	// revoke and gen-crl are one critical section, not two: a CRL generated
	// from a half-written index.txt would silently omit a revocation, and
	// the certificate it was meant to kill would keep working.
	if err := p.withPKILock(func() error {
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("openvpn: easyrsa revoke failed: %w (%s)", err, truncate(out, 400))
		}
		genCRL := exec.Command(p.easyrsaBin(), "gen-crl")
		genCRL.Dir = p.dir
		genCRL.Env = append(os.Environ(), "EASYRSA_BATCH=1")
		if out, err := genCRL.CombinedOutput(); err != nil {
			return fmt.Errorf("openvpn: easyrsa gen-crl failed: %w (%s)", err, truncate(out, 400))
		}
		return nil
	}); err != nil {
		return err
	}

	// Best-effort cleanup of the private key material for the revoked name;
	// the certificate stays on disk (easy-rsa's own index/db needs it) but
	// there is no reason to keep a copy of a now-useless private key around.
	_ = os.Remove(filepath.Join(p.dir, "pki", "private", name+".key"))
	return nil
}

// PublishCRL copies the freshly generated CRL to where the running openvpn
// server processes expect to find it (their `crl-verify` path). OpenVPN
// re-reads this file on every new connection attempt, so no server restart
// or signal is required for the revocation to start being enforced.
func (p *PKI) PublishCRL(destPath string) error {
	data, err := os.ReadFile(filepath.Join(p.dir, "pki", "crl.pem"))
	if err != nil {
		return fmt.Errorf("openvpn: reading generated crl.pem: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
		return err
	}
	// World-readable: the openvpn daemon (often running as the unprivileged
	// `nobody`/`openvpn` user) must be able to read it, and a CRL contains
	// no secrets — only serial numbers of revoked certs.
	return os.WriteFile(destPath, data, 0644)
}

func truncate(b []byte, n int) string {
	s := string(b)
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
