#!/usr/bin/env bash
# Refreshes the reklam/tracker blocklist unbound serves when threatProtection
# is enabled (POST /api/v1/settings). Meant to be run periodically by
# systemd/vpn-blocklist-update.timer, not as part of the one-time install
# sequence — safe to re-run any time, and never touches the live blocklist
# file unless the new one actually validates.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=./lib.sh
. ./lib.sh

require_root

SOURCE_URL="${VPN_BLOCKLIST_URL:-https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts}"
DEST=/etc/unbound/blocklists/blocklist.conf
TMP_RAW="$(mktemp)"
TMP_CONF="$(mktemp)"
trap 'rm -f "$TMP_RAW" "$TMP_CONF"' EXIT

log_info "Engelleme listesi indiriliyor: $SOURCE_URL"
if ! curl -fsSL --max-time 30 "$SOURCE_URL" -o "$TMP_RAW"; then
  log_err "İndirme başarısız; mevcut liste değiştirilmedi."
  exit 1
fi

{
  echo "# Generated by scripts/update-blocklist.sh on $(date -u +%FT%TZ) — do not edit by hand."
  echo "server:"
  awk '
    /^[[:space:]]*#/ { next }
    /^0\.0\.0\.0[[:space:]]+/ {
      domain = $2
      if (domain == "0.0.0.0" || domain == "localhost" || domain == "") { next }
      gsub(/"/, "", domain)
      printf "  local-zone: \"%s.\" always_nxdomain\n", domain
    }
  ' "$TMP_RAW"
} > "$TMP_CONF"

RULE_COUNT=$(grep -c "always_nxdomain" "$TMP_CONF" || true)
if [ "$RULE_COUNT" -lt 1000 ]; then
  log_err "Üretilen liste şüpheli şekilde küçük ($RULE_COUNT kural); kaynak biçim değişmiş olabilir. Uygulanmadı."
  exit 1
fi

if ! unbound-checkconf "$TMP_CONF" >/tmp/vpn-blocklist-check.log 2>&1; then
  log_err "Üretilen engelleme listesi unbound tarafından reddedildi:"
  cat /tmp/vpn-blocklist-check.log
  rm -f /tmp/vpn-blocklist-check.log
  exit 1
fi
rm -f /tmp/vpn-blocklist-check.log

install -m 644 "$TMP_CONF" "$DEST"
log_ok "$RULE_COUNT alan adı engellendi."

if command -v unbound-control >/dev/null 2>&1 && unbound-control status >/dev/null 2>&1; then
  unbound-control reload >/dev/null
  log_ok "unbound yeniden yüklendi."
else
  log_warn "unbound-control çalışmıyor; değişiklikler bir sonraki unbound yeniden başlatmasında etkinleşecek."
fi
